spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - profile

  thymeleaf:
    cache: false

  session:
    timeout: 1h
    cookie:
      http-only: true
      secure: false
      same-site: lax

server:
  port: 8080

app:
  session:
    timeout-seconds: 3600

security:
  level-mapping:
    lorenzo@gmail.com: SECRET
    teste@gmail.com: CONFIDENTIAL