spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - profile

  thymeleaf:
    cache: false

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/seguranca_computacional}
    username: ${DB_USER:app_user}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false        # true apenas para debug local
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  session:
    timeout: 1h
    cookie:
      http-only: true
      secure: false
      same-site: lax

server:
  port: 8080

app:
  session:
    timeout-seconds: 3600

security:
  level-mapping:
    lorenzo@gmail.com: SECRET
    teste@gmail.com: CONFIDENTIAL